### ISSUE TITLE
Sem erros - Obrigado

### ISSUE THREAD

**Issue by vitaoudi** [viniciusbig/tvleg#2]
tive problema para baixar:
Querying legendas.tv for Better.Call.Saul.S02E01.REPACK.720p.HDTV.x264-AVS.mkv
Terms: better call saul s02e01 avs
24 subtitles found. It can take a while to download it all.
Retrieving URL http://legendas.tv/downloadarquivo/56c3458512611
Traceback (most recent call last):
  File "tvleg.py", line 414, in <module>
    Application()
  File "tvleg.py", line 340, in **init**
    if self.s.search():
  File "tvleg.py", line 278, in search
    if self.d.get(url):
  File "tvleg.py", line 168, in get
    self.save()
  File "tvleg.py", line 191, in save
    pickle.dump( self.cache, open( self.config, "wb" ) )
IOError: [Errno 2] No such file or directory: './data/config'

Está buscando o arquivo config.

**Comment by vitaoudi** [comment]
Desculpe, estava com outra versão.

**Comment by viniciusbig** [comment]
Desculpe a demora!
Que bom que deu certo!
