### ISSUE TITLE
crontab erro

### ISSUE THREAD

**Issue by jeanmdg** [viniciusbig/tvleg#4]
Se eu executo o manualmente o tvleg.py ele baixo certinho a legenda, mas se eu colocar no crontab, ele aparece esse erro:

Traceback (most recent call last):
  File "/root/tvleg/tvleg.py", line 451, in <module>
    Application()
  File "/root/tvleg/tvleg.py", line 365, in **init**
    Downloader().clear()
  File "/root/tvleg/tvleg.py", line 149, in **init**
    with open(self.configFile) as data_file:
IOError: [Errno 2] No such file or directory: './data/config.json'

**Comment by viniciusbig** [comment]
ele está procurando o arquivo de configuração e não está encontrando.
provavelmente o crontab está usando seu próprio diretório como _basepath_.
Experimente alterar o código colocando o caminho completo do arquivo **config,json**
