### ISSUE TITLE
Falha ao tentar baixar legenda.

### ISSUE THREAD

**Issue by jeanmdg** [viniciusbig/tvleg#7]
Olá, esta acontecendo o seguinte erro quando tento baixar legendas:

Retrieving URL http://legendas.tv/downloadarquivo/5bfb87d2df853
Faile to retrieve URL http://legendas.tv/downloadarquivo/5bfb87d2df853

Teria alguma ideia o que pode ser?

Obrigado

**Comment by viniciusbig** [comment]
Olá!

sim..o site do Legendas TV começou a bloquear as requisições de robos com um 403.
Fiz um pequeno fix para tentar corrigir o problema, mas não sei até quando vai funcionar.

Teste novamente usando a tag 1.1.2
